exclude: '^\.idea/.*$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: master
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/doublify/pre-commit-isort
    rev: master
    hooks:
      - id: isort
        args:
          - --multi-line=3
          - --keep-direct-and-as
  - repo: https://github.com/ambv/black
    rev: master
    hooks:
      - id: black
        args:
          - -l 100
          - --py36
  - repo: local
    hooks:
      - id: prospector
        name: prospector
        entry: python -m prospector.__main__
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy
