# Generated by Django 2.1.3 on 2018-11-24 12:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("website", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="challenge", name="symbol", field=models.CharField(blank=True, max_length=6)
        )
    ]
